#!/bin/bash
git remote update;
git status -uall;

# commit
read -p "Are you sure, you want to commit? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 0
fi

git add -A;
git commit -m "sync";


# push
read -p "Are you sure, you want to push? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 0
fi

git push;
